# Generated by Django 6.0.2 on 2026-06-30 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_sourcefile_options_alter_sourcefile_file_hash_and_more'),
        ('generators', '0002_refactor_generation_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationrequest',
            name='question_types',
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with errors'), ('FAILED', 'Failed')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='GenerationRequestQuestionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_questions', models.PositiveSmallIntegerField()),
                ('generation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_configs', to='generators.generationrequest')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_question_configs', to='curriculum.lesson')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_question_configs', to='generators.questiontype')),
            ],
            options={
                'unique_together': {('generation_request', 'lesson', 'question_type')},
            },
        ),
    ]
