# Generated by Django 6.0.2 on 2026-07-03 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_project_ai_setup_fields'),
        ('generators', '0003_remove_generationrequest_question_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='curriculum.project'),
        ),
    ]
