import time
import uuid

from celery import shared_task
from django.utils import timezone

from .models import GenerationRequest, GeneratedQuestion


@shared_task
def process_generation_request(request_id):
    req = None
    try:
        req = GenerationRequest.objects.select_related('project').prefetch_related(
            'lessons__sources__source_file',
            'question_types',
        ).get(id=request_id)
        req.status = 'PROCESSING'
        req.save(update_fields=['status'])

        # TODO: Send lesson content and page ranges to the external AI microservice.
        time.sleep(1)

        for lesson in req.lessons.all():
            for question_type in req.question_types.all():
                GeneratedQuestion.objects.create(
                    lesson=lesson,
                    generation_request=req,
                    question_type=question_type,
                    content=f'Sample {question_type.name} question for {lesson.title}',
                    correct_answer='Sample answer',
                    distractors=['Option A', 'Option B', 'Option C'] if question_type.code == 'mcq' else [],
                    explanation='Generated by stub task.',
                    chunk_hash=str(uuid.uuid4()),
                )

        req.status = 'COMPLETED'
        req.completed_at = timezone.now()
        req.save(update_fields=['status', 'completed_at'])

    except GenerationRequest.DoesNotExist:
        pass
    except Exception as exc:
        if req is None:
            req = GenerationRequest.objects.filter(id=request_id).first()
        if req:
            req.status = 'FAILED'
            req.error_log = str(exc)
            req.completed_at = timezone.now()
            req.save(update_fields=['status', 'error_log', 'completed_at'])
