# Generated by Django 6.0.2 on 2026-06-30 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_sourcefile_and_lessonsource_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcefile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='file_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='sourcefile',
            index=models.Index(fields=['owner', 'file_hash'], name='curriculum__owner_i_61839b_idx'),
        ),
    ]
