# Generated by Django 6.0.2 on 2026-07-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_lesson_grouping_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='domain',
            field=models.CharField(choices=[('grammar', 'Grammar'), ('vocab', 'Vocabulary')], default='grammar', max_length=20),
        ),
    ]
