# Generated by Django 6.0.2 on 2026-07-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_lesson_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='domain',
            field=models.CharField(choices=[('english_vocab', 'Vocabulary'), ('english_syn_ant', 'Synonyms & Antonyms'), ('english_def_der_col', 'Definition, Derivatives & Verbal Collocation'), ('english_exp_idi_prep', 'Expression, Idioms & Prepositions'), ('english_grammar', 'Grammar')], default='english_vocab', max_length=40),
        ),
    ]
