# Generated by Django 6.0.2 on 2026-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_lesson_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='domain',
            field=models.CharField(blank=True, choices=[('english_vocab', 'Vocabulary'), ('english_syn_ant', 'Synonyms & Antonyms'), ('english_def_der_col', 'Definition, Derivatives & Verbal Collocation'), ('english_exp_idi_prep', 'Expression, Idioms & Prepositions'), ('english_grammar', 'Grammar')], default='english_vocab', max_length=40),
        ),
    ]
